website/blog/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.home, name = 'home'),
    url(r'^(?P<post_pk>[0-9]+)/$', views.post_detail, name = 'post_detail'),
    url(r'^signup/$', views.signup, name = 'signup'),
    url(r'^login/$', views.login, name = 'login'),
    url(r'^logout/$', views.logout, name = 'logout'),
    url(r'^userpage/$', views.userpage, name = 'userpage'),
    url(r'^userlist/$', views.userlist, name = 'userlist'),
    url(r'^userfollow/(?P<username>\w+)/$', views.user_follow, name = 'user_follow'),
    url(r'^following/$', views.following, name = 'following'),
    url(r'^userhome/$', views.user_home, name = 'user_home'),
    url(r'^userposts/$', views.user_posts, name = 'user_posts'),
    url(r'^writepost/$', views.write_post, name = 'write_post'),
    url(r'^delete_post/(?P<post_pk>[0-9]+)/$', views.delete_post, name = 'delete_post'),
    url(r'^comment/(?P<post_pk>[0-9]+)/$', views.comment, name = 'comment'),
    url(r'^export_xlsx/$', views.export_xlsx, name = 'export_xlsx'),
]

website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
]

website/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

#Comment to self: Change User to settings.AUTH_USER_MODEL (django.contrib.auth) 
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, related_name = 'user_profile')
    follow = models.ManyToManyField(User, related_name = 'user_follow')
    dob = models.DateField(null=True)
    mobile_no = models.IntegerField(null=True)
    interests = models.CharField(max_length = 200,null=True)

    def __str__(self):
        return self.user.username

class Post(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 100)
    content = models.CharField(max_length = 1000)
    pub_date = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pub_date']

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    comment = models.CharField(max_length = 200)

    def __str__(self):
        return self.comment

website/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate
from django.contrib.auth import logout as django_logout
from django.contrib.auth import login as django_login
from django.contrib.auth.models import User
from django.http import Http404, HttpResponse
from .models import Post, UserProfile, Comment
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import datetime
import openpyxl as opxl
from openpyxl.writer.excel import save_virtual_workbook
# Create your views here.


def home(request):
    if request.user.is_authenticated():
        return redirect('blog:userpage')
    else:
        return redirect('blog:login')

#Sign-Up, Login and Logout

def signup(request):
    #Displays sign-up page
    if request.method == 'GET':
        return render(request, 'blog/signup.html')
    #Signs up the user
    elif request.method =='POST':
        fname = request.POST['fname']
        lname = request.POST['lname']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password_re = request.POST['password_re']


        if fname.isalpha() and lname.isalpha() and username.isalnum():
            if password == password_re:
                #Creates User
                user = User(username = username, email = email, first_name = fname, last_name = lname)
                user.set_password(password)
                user.save()
                #Creates User Profile
                userprofile = UserProfile(user=user)
                userprofile.save()

                return render(request, 'blog/login.html')

            else:
                messages.error(request, "Your passwords don't match!")
                return redirect('blog:signup')

        else:
            messages.error(request, "Please fill all the fields!")
            return redirect('blog:signup')



def login(request):
    #Display the login page
    if request.method == 'GET':
        return render(request, 'blog/login.html')
    #Logging user into the website
    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        print("username: {}, password: {}".format(username, password))
        user = authenticate(username = username, password = password)
        print user

        if user is not None:
            django_login(request, user)
            messages.success(request, "Successful Login")
            return redirect('blog:userpage')
        else:
            messages.error(request, "Please enter the correct credentials and try again!")
            return redirect('blog:login')

def logout(request):
    django_logout(request)
    return redirect('blog:home')

#Following views are only for logged in users

@login_required
def userpage(request):
    my_user = request.user
    return render(request, 'blog/userpage.html', {'user':my_user,})

@login_required
def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk = post_pk)
    comments = post.comment_set.all()
    return render(request, 'blog/post_detail.html', {'post':post, 'comments':comments,})

@login_required
def userlist(request):
    my_user = request.user
    userlist = User.objects.exclude(pk = my_user.pk)
    return render(request, 'blog/userlist.html', {'userlist':userlist})

@login_required
def user_follow(request, username):
    my_user =  request.user
    user = User.objects.get(username = username)
    my_userprofile = my_user.user_profile
    my_userprofile.follow.add(user)
    return redirect('blog:following')

@login_required
def following(request):
    my_user = request.user
    userprofile = my_user.user_profile
    follow_list = userprofile.follow.all()
    return render(request, 'blog/following.html', {'follow_list':follow_list,})

@login_required
def user_home(request):
    my_user = request.user
    follow_list = my_user.user_profile.follow.all()
    post_list = list()
    for user in follow_list:
        for post in user.post_set.all():
            post_list.append(post)
    for i in range(0, len(post_list)-1):
        for j in range(i+1, len(post_list)):
            if post_list[i].pub_date < post_list[j].pub_date:
                post_list[i], post_list[j] = post_list[j], post_list[i]
    return render(request, 'blog/user_home.html', {'post_list':post_list})

@login_required
def user_posts(request):
    my_user = request.user
    posts = my_user.post_set.all()
    return render(request, 'blog/user_posts.html', {'posts':posts})

@login_required
def write_post(request):
    if request.method == 'GET':
        return render(request, 'blog/write_post.html')
    elif request.method == 'POST':
        my_user = request.user
        title = request.POST['title']
        content = request.POST['content']
        pub_date = datetime.datetime.now()
        post = Post(user = my_user, title = title, content = content)
        post.save()
        return redirect('blog:post_detail', post_pk = post.pk)

@login_required
def comment(request, post_pk):
    my_user = request.user
    post = Post.objects.get(pk = post_pk)
    comment_text = request.POST['comment']
    comment = Comment(user = my_user, post = post, comment = comment_text)
    comment.save()
    return post_detail(request, post_pk)

@login_required
def delete_post(request, post_pk):
    post = Post.objects.get(pk = post_pk)
    post.delete()
    return userpage(request, request.user.username)


def export_xlsx(request):
    user_list = User.objects.exclude(username = 'admin')
    wb = opxl.Workbook()
    ws = wb.active
    ws.title = 'User Information'

    ws['A1'] = "Primary Key"
    ws['B1'] = "First Name"
    ws['C1'] = "Last Name"
    ws['D1'] = "Username"
    ws['E1'] = "Email"
    ws['F1'] = "DOB"
    ws['G1'] = "Mobile No"

    for user in user_list:
        ws['A{}'.format(user.pk+1)] = user.pk
        ws['B{}'.format(user.pk+1)] = user.first_name
        ws['C{}'.format(user.pk+1)] = user.last_name
        ws['D{}'.format(user.pk+1)] = user.username
        ws['E{}'.format(user.pk+1)] = user.email
        ws['F{}'.format(user.pk+1)] = user.user_profile.dob
        ws['G{}'.format(user.pk+1)] = user.user_profile.mobile_no

    response = HttpResponse(save_virtual_workbook(wb), content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename = "user_info.xlsx"'
    return response

website/blog/templates/blog/following.html
<html>

<head>
  <title>Followinglist</title>
</head>

<body style = "background-color:powderblue;">
  <h1 style = "font-size:40px; color:red;">Following List</h1><br>
  {% if follow_list %}
    <ul>
    {% for user in follow_list %}
        <li style = "font-size:30px; color:black">
        <a href = "{% url 'blog:userpage' %}">
        {{ user.username }} </a> </li>
    {% endfor %}
    </ul>
  {% else %}
    <h2 style = "font-size:30px;"> You are not following anyone. </h2>
  {% endif %}

  <br>
  <a href = "{% url 'blog:userlist' %}"> User List </a>

</body>

</html>

website/blog/templates/blog/login.html
<html>

<head>
  <title>Login</title>
</head>

<body style = "background-color:powderblue;">
  <h1 style = "font-size:40px; color:red;">Login</h1><br>

  {% if messages %}
    {% for message in messages %}
      <p class = "{{ message.tags }}" style = "color:red">{{ message }}</p>
    {% endfor %}
  {% endif %}

  <form action = "{% url 'blog:login' %}" method = "post">
  {% csrf_token %}
  <label for = 'username'><h2 style = "font-size:20px;"> UserName: </h2></label>
    <input type = 'text' name = 'username'><br>
  <label for = 'password'><h2 style = "font-size:20px;"> Password: </h2></label>
    <input type = 'password', name = 'password'><br>
  <input type = 'submit', value = 'submit'>
  </form>
  <br>
  <h2 style = "font-size:20px"> To create an account, click below. </h1>
  <p><a href = {% url 'blog:signup' %}> Sign Up </a>

</body>

</html>

website/blog/templates/blog/post_detail.html
<html>

<head>
  <title>Post</title>
</head>

<body style = "background-color:powderblue">
  <h1 style = "font-size:40px; color:red">Welcome to post {{post.pk}}!</h1>
  {% if post %}
    <h2 style = "font-size:30px;"> {{ post.content }} </h2>
    <br><br>
    <h2 style = "font-size:30px;"> Comment </h2>
    {% if comments %}
      <ul>
      {% for comment in comments %}
        <li style = "font-size:20px;"> {{comment.user}} : {{comment.comment}} </li>
      {% endfor %}
      </ul>
    {% endif %}
    <form action = "{% url 'blog:comment' post.pk %}" method = "post">
      {% csrf_token %}
      <label for = 'comment' style = "font-size:20px;"> comment: </label>
      <input type = 'text' name = 'comment'><br>
      <input type = 'submit', value = 'submit'>
    </form>
  {% else %}
    <h2 style = "font-size:30px;"> Post DOES NOT EXIST!! </h2>
  {% endif %}
</body>

<a href = "{% url 'blog:userlist' %}"> User List </a><br>
<a href = "{% url 'blog:following' %}"> Follow List </a><br>
<a href = "{% url 'blog:write_post' %}"> Write Post </a><br>
<a href = "{% url 'blog:user_home' %}"> User Home </a><br>
<a href = "{% url 'blog:user_posts' %}"> My Posts </a><br>
<a href = "{% url 'blog:logout' %}"> Logout </a><br>

</html>

website/blog/templates/blog/signup.html
<html>

<head>
  <title>SignUp</title>
</head>

<body style = "background-color:powderblue;">
  <h1 style = "font-size:40px; color:red;">Sign Up</h1><br>

  {% if messages %}
    {% for message in messages %}
      <p class = "{{ message.tags }}" style = "color:red">{{ message }}</p>
    {% endfor %}
  {% endif %}

  <form action = "{% url 'blog:signup' %}" method = "post">
  {% csrf_token %}
  <label for = 'fname'><h2 style = "font-size:20px;"> First Name: </h2></label>
    <input type = 'text' name = 'fname'><br>
  <label for = 'lname'><h2 style = "font-size:20px;"> Last Name: </h2></label>
    <input type = 'text' name = 'lname'><br>
  <label for = 'username'><h2 style = "font-size:20px;"> UserName: </h2></label>
    <input type = 'text' name = 'username'><br>
  <label for = 'email'><h2 style = "font-size:20px;"> Email: </h2></label>
    <input type = 'text', name = 'email'><br>
  <label for = 'password'><h2 style = "font-size:20px;"> Password: </h2></label>
    <input type = 'password', name = 'password'><br>
  <label for = 'password_re'><h2 style = "font-size:20px;"> Re-enter Password: </h2></label>
    <input type = 'password', name = 'password_re'><br>
  <input type = 'submit', value = 'submit'>
  </form>
</body>

</html>

website/blog/templates/blog/user_home.html
<html>

<head>
  <title>UserHome</title>
</head>

<body style = "background-color:powderblue;">
  <h1 style = "font-size:40px; color:red;">User Home</h1><br>
  {% if post_list %}
    <ul>
      {% for post in post_list %}
      <li style = "font-size:20px">
        <a href = "{% url 'blog:post_detail' post.pk %}">
        {{ post.title }}
        </a></li>
      {% endfor %}
    </ul>
  {% else %}
    <h2 style = "font-size:30px;"> No posts are available. </h2>
  {% endif %}

  <br><a href = "{% url 'blog:userpage' %}"> User Page </a><br>
  <a href = "{% url 'blog:userlist' %}"> User List </a><br>
  <a href = "{% url 'blog:following' %}"> Follow List </a><br>
  <a href = "{% url 'blog:write_post' %}"> Write Post </a><br>
  <a href = "{% url 'blog:user_posts' %}"> My Posts </a><br>
  <a href = "{% url 'blog:logout' %}"> Logout </a><br>

</body>

</html>

website/blog/templates/blog/user_posts.html
<html>

<head>
  <title>UserPosts</title>
</head>

<body style = "background-color:powderblue;">
  <h1 style = "font-size:40px; color:red;">My Posts</h1><br>
  {% if posts %}
    <ul>
      {% for post in posts %}
        <li style = "font-size:20px">
        <a href = "{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a>
        <a href = "{% url 'blog:delete_post' post.pk %}"> delete</a>      
        </li>
      {% endfor %}
      </ul>
  {% else %}
    <h2 style = "font-size:30px;"> No posts are available. </h2>
  {% endif %}

</body>

</html>

website/blog/templates/blog/userlist.html
<html>

<head>
  <title>Userlist</title>
</head>

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

<body style = "background-color:powderblue;">
  <h1 style = "font-size:40px; color:red;">User List</h1><br>
  {% if userlist %}
    <ul>
    {% for user in userlist %}
        <li style = "font-size:30px; color:black">
        <a href = "{% url 'blog:userpage' %}"> {{ user.username }} </a><br>
        <a href = "{% url 'blog:user_follow' user.username %}"> Follow </a><br>
        </li>
    {% endfor %}
    </ul>
  {% else %}
    <h2 style = "font-size:30px;"> No users are available. </h2>
  {% endif %}

</body>

</html>

website/blog/templates/blog/userpage.html
<html>

<head>
  <title>Userpage</title>
</head>

<body style = "background-color:powderblue;">
  <h1 style = "font-size:40px; color:red;">User Page</h1><br>

  {% if messages %}
    {% for message in messages %}
      <p class = "{{ message.tags }}" style = "color:red">{{ message }}</p>
    {% endfor %}
  {% endif %}

  {% if user %}
    <ul>
      <li style = "font-size:30px; color:black">First Name: {{user.first_name}}</li>
      <li style = "font-size:30px; color:black">Last Name: {{user.last_name}}</li>
      <li style = "font-size:30px; color:black">User Name: {{user.username}}</li>
    </ul>
  {% else %}
    <h2 style = "font-size:30px;"> Error!! </h2>
  {% endif %}

  <br>
  <a href = "{% url 'blog:userlist' %}"> User List </a><br>
  <a href = "{% url 'blog:following' %}"> Follow List </a><br>
  <a href = "{% url 'blog:write_post' %}"> Write Post </a><br>
  <a href = "{% url 'blog:user_home' %}"> User Home </a><br>
  <a href = "{% url 'blog:user_posts' %}"> My Posts </a><br>
  <a href = "{% url 'blog:logout' %}"> Logout </a><br>

</body>

</html>

website/blog/templates/blog/write_post.html
<html>

<head>
  <title>WritePost</title>
</head>

<body style = "background-color:powderblue;">
  <h1 style = "font-size:40px; color:red;">Write Post</h1><br>
  <form action = "{% url 'blog:write_post' %}" method = "post">
  {% csrf_token %}
  <label for = 'title'><h2 style = "font-size:20px;"> Title: </h2></label>
    <input type = 'text' name = 'title'><br>
  <label for = 'content'><h2 style = "font-size:20px;"> Content: </h2></label>
    <input type = 'text' name = 'content'><br>
  <input type = 'submit', value = 'submit'>
  </form>
</body>

</html>